In [192]:
import matplotlib
import pathlib
import os.path
from os import path
import mne
import mne_bids #brain imaging data structure #convert dataset to bits compatible dataset, .fif is actual data, will be able to run tools that expect bits data
from bids_validator import BIDSValidator
import numpy as np

In [193]:
matplotlib.use('Qt5Agg')  #interactive

In [194]:
data_path="/Users/Asmita_Hajra/Downloads/bidsexport" #path of BIDS data

## Structure of directory

In [164]:
mne_bids.print_dir_tree(data_path)

|bidsexport/
|--- .DS_Store
|--- CHANGES
|--- README
|--- dataset_description.json
|--- epochs_epo.fif
|--- evokeds_ave.fif
|--- participants.json
|--- participants.tsv
|--- task-meditation_events.json
|--- code/
|------ run_mw_experiment6.m
|--- stimuli/
|------ cancel.wav
|------ depth.wav
|------ expe_over.wav
|------ mind_wandering.wav
|------ rate_meditation.wav
|------ rate_mw.wav
|------ rate_tired.wav
|------ resume.wav
|------ resumed.wav
|------ resumemed.wav
|------ self.wav
|------ starting.wav
|------ time.wav
|------ valence.wav
|--- sub-001/
|------ .DS_Store
|------ ses-01/
|--------- .DS_Store
|--------- eeg/
|------------ sub-001_ses-01_task-meditation_channels.tsv
|------------ sub-001_ses-01_task-meditation_eeg.bdf
|------------ sub-001_ses-01_task-meditation_eeg.json
|------------ sub-001_ses-01_task-meditation_events.tsv
|------------ .ipynb_checkpoints/
|--------------- sub-001_ses-01_task-meditation_channels-checkpoint.tsv
|--------------- sub-001_ses-01_task-me

## Report

In [165]:
print(mne_bids.make_report(data_path)) #path to bids directory #doubt, no authors thus error

KeyError: 'Authors'

## Reading BIDS data-> analyzing raw data



In [195]:
# currently for finding X of dataset
def load_and_epoch_data(n): # n= no. of subjects 
     # INPUT: NUMBER OF SUBJECTS DATASET TO BE LOADED
     # OUTPUT: list of 2d array (length = no. of subjects * 2)
    raw_data_np=[]
    raw_data=[]
    subject_id=''
    session_id=''
    for i in range(n): #0-23
        for j in range(3): # no. of sessions
            # i is the subject number
            # j is the session number
            if(i<9):
                subject_id="00"+str(i+1)
            else:
                subject_id="0"+str(i+1)
                
            session_id="0"+str(j+1)
            
            # check if path exists 
            # print("hello"+ str(i)+""+str(j))
            dataset_path_to_validate=data_path+"/sub-"+subject_id+"/ses-"+session_id
            if(path.isdir(dataset_path_to_validate)): #validating if these sessions exist
                list_of_files = os.listdir(dataset_path_to_validate+"/eeg") # Checking if the folder is empty
                if len(list_of_files) != 0:
                    bids_path = mne_bids.BIDSPath(subject=subject_id, 
                              session=session_id,
                              task='meditation',
                              # run='01', #doubt what is run number
                              datatype='eeg', #will have a folder with datatype as name
                              root=data_path)
#                 if(BIDSValidator().is_bids(dataset_path_to_validate+"/eeg")):
#                     print("hellp")
                    raw = mne_bids.read_raw_bids(bids_path)
                    # print(raw.shape)'RawEDF', object has no attribute 'shape'
                    data, times = raw[:] # converting to ndarray
                    print (data.shape)
                    raw_data_np.append(data)
                    raw_data.append(raw) # list of raw data

    return raw_data, raw_data_np

no_of_subjects= 24
raw_data, raw_data_np = load_and_epoch_data(no_of_subjects)

Extracting EDF parameters from /Users/Asmita_Hajra/Downloads/bidsexport/sub-001/ses-01/eeg/sub-001_ses-01_task-meditation_eeg.bdf...
BDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading events from /Users/Asmita_Hajra/Downloads/bidsexport/sub-001/ses-01/eeg/sub-001_ses-01_task-meditation_events.tsv.
The event "response" refers to multiple event values. Creating hierarchical event names.
    Renaming event: response -> response/2
    Renaming event: response -> response/2
    Renaming event: response -> response/2
    Renaming event: response -> response/4
    Renaming event: response -> response/2
    Renaming event: response -> response/2
    Renaming event: response -> response/2
    Renaming event: response -> response/2
    Renaming event: response -> response/2
    Renaming event: response -> response/4
    Renaming event: response -> response/4
    Renaming event: response -> response/2
    Renaming event: response -> response/2
    Renaming 

In [180]:
len(raw_data_np)

40

In [181]:
type(raw_data_np)

list

In [ ]:
# Saving the ndarray
arr = np.empty(40, object) # 40 objects
arr[:] = raw_data_np
np.save('/Users/Asmita_Hajra/mne-research/stored_data.npy', arr) # save

In [80]:
# Loading the nd array
loaded_raw_data = np.load('/Users/Asmita_Hajra/mne-research/stored_data.npy', allow_pickle=True) # load


In [18]:
# finding maximum no. of events

for i in range(40):
    events=mne.find_events(raw_data[i]) 
    
#Observation-> Max no of events-> 2, 4, 8, 128, 254

<class 'mne.io.edf.edf.RawEDF'>
<class 'mne.io.edf.edf.RawEDF'>
Trigger channel has a non-zero initial value of 65536 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
87 events found
Event IDs: [  2   4 128]
Trigger channel has a non-zero initial value of 65536 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
87 events found
Event IDs: [  2   4 128]
Trigger channel has a non-zero initial value of 65536 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
101 events found
Event IDs: [  2   4 128]
Trigger channel has a non-zero initial value of 65536 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
107 events found
Event IDs: [  2   4 128]
Trigger channel has a non-zero initial value of 65536 (consider using initial_event=True to detect this ev


## About data
#### Stimulus is 128-> Onset of first Question
#### Response -> Response to question 1, 2 or 3
#### doubt what is STATUS-> 254
#### "2"-> Response 1 (this may be a response to question 1, 2 or 3)"
#### "4"-> Response 2 (this may be a response to question 1, 2 or 3)"
#### "8"-> Response 3 (this may be a response to question 1, 2 or 3)"
#### "16"-> involuntary response
#### "128"-> First question onset (most important marker)

## Finding info and visualizing for one subject's session

In [12]:
print(raw_data[3].info) # 68 EEG channels

<Info | 9 non-empty values
 bads: []
 ch_names: A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, ...
 chs: 68 EEG, 10 MISC, 1 RESP, 1 STIM
 custom_ref_applied: False
 highpass: 0.0 Hz
 line_freq: 50
 lowpass: 52.0 Hz
 meas_date: 2014-04-12 16:57:33 UTC
 nchan: 80
 projs: []
 sfreq: 256.0 Hz
 subject_info: 4 items (dict)
>


In [170]:
print(type(raw_data[0]))
# raw_data[0].plot()
events = mne.find_events(raw_data[0]) # 3 events, [  2   4 128]

# raw_data[5].plot()
events = mne.find_events(raw_data[5]) # 4 events, [  2   4   8 128]

raw_data[21].plot()
events = mne.find_events(raw_data[21]) # 5 events, [  2   4   8 128 254]

#events are actually stored as annotations
raw_data[21].annotations[0] 
raw_data[21].annotations[1]
events, event_id = mne.events_from_annotations(raw_data[21])
print("events and event_id", events, event_id)
print("events array shape", events.shape)

# doubt difference in response/2 vs response/4 vs response/8
print("no of event response/8", len(events[events[:, 2] == 4])) #all rows with event no 8
print(raw_data[21].info)
print("measuring date", raw_data[21].info['meas_date'])
print("sampling frequency",raw_data[21].info['sfreq']) #number of samples/second-> 256
print("line frquency", raw_data[21].info['line_freq']) #line frequency
print("subject information", raw_data[21].info['subject_info'])
print("events are now annotations", raw_data[21].annotations)
print("bads", raw_data[21].info['bads']) #none here
print("10 channel names", raw_data[21].ch_names[:10])
print("info of a channel", raw_data[21].info['chs'][0])

<class 'mne.io.edf.edf.RawEDF'>
Trigger channel has a non-zero initial value of 65536 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
87 events found
Event IDs: [  2   4 128]
Trigger channel has a non-zero initial value of 65536 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
79 events found
Event IDs: [  2   4   8 128]
Trigger channel has a non-zero initial value of 65536 (consider using initial_event=True to detect this event)
Removing orphaned offset at the beginning of the file.
113 events found
Event IDs: [  2   4   8 128 254]
Used Annotations descriptions: ['STATUS', 'response/2', 'response/4', 'response/8', 'stimulus']
events and event_id [[  3162      0      1]
 [  8547      0      5]
 [  9803      0      2]
 [ 10769      0      4]
 [ 11444      0      3]
 [ 44471      0      5]
 [ 45711      0      3]
 [ 47385      0      4]
 [ 47970      0      3]
 [

## Asserting uniformity of data and applying montage

In [129]:
f=open("/Users/Asmita_Hajra/mne-research/biosemi64.txt","r")
lines=f.readlines()
result=[]
for x in lines:
    result.append(x.split('\t')[0])
f.close()

In [130]:
print(result)

['Site', 'Fp1', 'AF7', 'AF3', 'F1', 'F3', 'F5', 'F7', 'FT7', 'FC5', 'FC3', 'FC1', 'C1', 'C3', 'C5', 'T7', 'TP7', 'CP5', 'CP3', 'CP1', 'P1', 'P3', 'P5', 'P7', 'P9', 'PO7', 'PO3', 'O1', 'Iz', 'Oz', 'POz', 'Pz', 'CPz', 'Fpz', 'Fp2', 'AF8', 'AF4', 'AFz', 'Fz', 'F2', 'F4', 'F6', 'F8', 'FT8', 'FC6', 'FC4', 'FC2', 'FCz', 'Cz', 'C2', 'C4', 'C6', 'T8', 'TP8', 'CP6', 'CP4', 'CP2', 'P2', 'P4', 'P6', 'P8', 'P10', 'PO8', 'PO4', 'O2', 'Nz', 'LPA', 'RPA']


In [196]:
biosemi_montage = mne.channels.make_standard_montage('biosemi64')
biosemi_montage.plot(show_names=True)

Creating RawArray with float64 data, n_channels=64, n_times=1
    Range : 0 ... 0 =      0.000 ...     0.000 secs
Ready.


<Figure size 1280x1280 with 1 Axes>

In [197]:
# making dictionary to map channels to 10-20 biosemi64 montage format

channel_keys = ['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'A11', 'A12', 'A13', 'A14', 'A15', 'A16', 'A17', 'A18', 'A19', 'A20', 'A21', 'A22', 'A23', 'A24', 'A25', 'A26', 'A27', 'A28', 'A29', 'A30', 'A31', 'A32', 'B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B9', 'B10', 'B11', 'B12', 'B13', 'B14', 'B15', 'B16', 'B17', 'B18', 'B19', 'B20', 'B21', 'B22', 'B23', 'B24', 'B25', 'B26', 'B27', 'B28', 'B29', 'B30', 'B31', 'B32']
montage_keys= ['Fp1', 'AF7', 'AF3', 'F1', 'F3', 'F5', 'F7', 'FT7', 'FC5', 'FC3', 'FC1', 'C1', 'C3', 'C5', 'T7', 'TP7', 'CP5', 'CP3', 'CP1', 'P1', 'P3', 'P5', 'P7', 'P9', 'PO7', 'PO3', 'O1', 'Iz', 'Oz', 'POz', 'Pz', 'CPz', 'Fpz', 'Fp2', 'AF8', 'AF4', 'AFz', 'Fz', 'F2', 'F4', 'F6', 'F8', 'FT8', 'FC6', 'FC4', 'FC2', 'FCz', 'Cz', 'C2', 'C4', 'C6', 'T8', 'TP8', 'CP6', 'CP4', 'CP2', 'P2', 'P4', 'P6', 'P8', 'P10', 'PO8', 'PO4', 'O2'] #without Nz, LPA, RPA

res_channels = {channel_keys[i]: montage_keys[i] for i in range(len(channel_keys))}

for i in range(40):
    raw_data[i].rename_channels(res_channels)

In [22]:
# lets assert a few things to find distribution of data
# sfreq, no. of channels, whether they have valid subject info

# do with loaded raw data later
# print(type(loaded_raw_data)) 
# print(loaded_raw_data.shape) # 40
# print(loaded_raw_data[0].shape) # (80, 696576)
# for i in range(40): #0-23
#         assert(loaded_raw_data[i].shape[0]==80) # checking if all have equal channels

In [202]:
# lets assert a few things to find distribution of data
# sfreq, no. of channels, whether they have valid subject info

print(len(raw_data_np)) # 40
print(raw_data_np[0].shape) # (80, 696576)
for i in range(40): #0-23
        assert(raw_data_np[i].shape[0]==80) # checking if all have equal channels
        assert(raw_data[i].info['sfreq']==256) # checking if all have equal sfreq
        assert((raw_data[i].info['subject_info']['group']=='expert') or (raw_data[i].info['subject_info']['group']=='novice')) # checking if all have group defined
        assert((raw_data[i].info['highpass']==0) and (raw_data[i].info['lowpass']==52.0)) # all highpass and lowpass same        
        ############################
        ###Applying montage###
        raw_data[i].set_montage(biosemi_montage, on_missing="ignore") #missing-> ['GSR1', 'GSR2', 'Plet', 'Temp'].; DigMontage is subset
        ###Dropping non-eeg channels###
        raw_data[i].drop_channels(['EXG1', 'EXG2', 'EXG3', 'EXG4', 'EXG5', 'EXG6', 'EXG7', 'EXG8', 'GSR1', 'GSR2', 'Erg1', 'Erg2', 'Resp', 'Plet', 'Temp'])
        #channel_indices=mne.pick_types(raw_data[i].info, eeg=True, exclude=['Temp', 'Plet', 'GSR1', 'GSR2'])
        channel_indices=mne.pick_types(raw_data[i].info, eeg=True)
        assert(len(channel_indices)==64) # all have 64 EEG channels
        print(raw_data[i].info['ch_names'])
        assert(len(raw_data[i].info['bads'])==0) # no bad channels

40
(80, 696576)
['Fp1', 'AF7', 'AF3', 'F1', 'F3', 'F5', 'F7', 'FT7', 'FC5', 'FC3', 'FC1', 'C1', 'C3', 'C5', 'T7', 'TP7', 'CP5', 'CP3', 'CP1', 'P1', 'P3', 'P5', 'P7', 'P9', 'PO7', 'PO3', 'O1', 'Iz', 'Oz', 'POz', 'Pz', 'CPz', 'Fpz', 'Fp2', 'AF8', 'AF4', 'AFz', 'Fz', 'F2', 'F4', 'F6', 'F8', 'FT8', 'FC6', 'FC4', 'FC2', 'FCz', 'Cz', 'C2', 'C4', 'C6', 'T8', 'TP8', 'CP6', 'CP4', 'CP2', 'P2', 'P4', 'P6', 'P8', 'P10', 'PO8', 'PO4', 'O2', 'Status']
['Fp1', 'AF7', 'AF3', 'F1', 'F3', 'F5', 'F7', 'FT7', 'FC5', 'FC3', 'FC1', 'C1', 'C3', 'C5', 'T7', 'TP7', 'CP5', 'CP3', 'CP1', 'P1', 'P3', 'P5', 'P7', 'P9', 'PO7', 'PO3', 'O1', 'Iz', 'Oz', 'POz', 'Pz', 'CPz', 'Fpz', 'Fp2', 'AF8', 'AF4', 'AFz', 'Fz', 'F2', 'F4', 'F6', 'F8', 'FT8', 'FC6', 'FC4', 'FC2', 'FCz', 'Cz', 'C2', 'C4', 'C6', 'T8', 'TP8', 'CP6', 'CP4', 'CP2', 'P2', 'P4', 'P6', 'P8', 'P10', 'PO8', 'PO4', 'O2', 'Status']
['Fp1', 'AF7', 'AF3', 'F1', 'F3', 'F5', 'F7', 'FT7', 'FC5', 'FC3', 'FC1', 'C1', 'C3', 'C5', 'T7', 'TP7', 'CP5', 'CP3', 'CP1', 'P1'

In [207]:
#checking plotted sensors for one subject
raw_data[21].plot_sensors(ch_type='eeg')
raw_data[21].plot_sensors(kind='3d', ch_type='eeg')


<Figure size 1280x1280 with 1 Axes>